# _config.yml
title: Ray Fraley Photography
theme: minima   # (or your theme)
markdown: kramdown
permalink: pretty
url: "https://www.rayfraley.com"
baseurl: ""
collections: []  # we’re using folders, not collections
defaults:
  - scope: {path: ""}        # site-wide defaults
    values:
      layout: default
      nav: true
